### ISSUE TITLE
Qt 5.4.2 Mingw Craxh app

### ISSUE THREAD

**Issue by bellicheone** [GreatTux/CefMinGWQt#2]
bonjour j'ai compilé la solution avec QT Win 5.4.2 et cmake 3.3.0. j'ai pris la version CEF 3.2272.32
la compilation passe sans problème.

par contre, à l'exectuion, j'ai un crash dans l'appel de CEF_REQUIRE_UI_THREAD dans la function ci-dessous.

CefRefPtr<CefBrowser> ClientHandler::GetBrowser() const
{
    CEF_REQUIRE_UI_THREAD();

```
return m_browser;
```

}

Je ne trouve pas la source de ce problème. avez vous une idée de crash ?

**Comment by GreatTux** [comment]
Bonjour,

À quel moment survient ce crash ? Pouvez-vous fournir une stack trace ?

**Comment by bellicheone** [comment]
Cela se produit au lancement de cefqtclient
//*********************
//function dans le fichier libcef_dll_wrapper.cc
CEF_GLOBAL bool CefCurrentlyOn(CefThreadId threadId) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = cef_currently_on(threadId); // <= crash ici

  // Return type: bool
  return _retval?true:false;
}

//*********************
//info du stack
CefCurrentlyOn
ClientHandler::GetBrowser()
MainWindow::resizeEvent

//*********************
//voilà la trace du debuggeur
[0629/174301:FATAL:libcef_dll_wrapper.cc(152)] Check failed: false. 

Backtrace:
    cef_trace_event_instant [0x12CB5181+1457409]
    cef_trace_event_instant [0x12BE448F+602127]
    cef_log [0x12B4E842+82](No symbol) [0x00408AF4](No symbol) [0x004039DA](No symbol) [0x004027FE](No symbol) [0x004013DE]
    BaseThreadInitThunk [0x7562336A+18]
    RtlInitializeExceptionChain [0x77689F72+99]
    RtlInitializeExceptionChain [0x77689F45+54]

**Comment by GreatTux** [comment]
CEF_REQUIRE_UI_THREAD(); vérifie que l'appel à cette méthode est bien effectuée dans le Thread UI, ce qui ne semble pas être le cas ici, pour une raison que j'ignore. Cela explique l'arrêt de l'exécution du programme.
Avez-vous une particularité dans votre environnement de travail qui pourrait l'expliquer ?

Juste pour vérifier, j'ai testé avec Qt 5.4.0 (seule version de 5.4 que j'ai sous la main) sans problème. C'est la seule différence notable d'environnement par rapport au mien.

**Comment by bellicheone** [comment]
non je n'est rien de particulier.

j'utilise mingw 4.9.1. J'ai aussi testé avec Qt 5.2.0 et mingw 4.8 mais le résultat et le même.

J'ai également refait les tests avec Qt 5.4.2 avec mingw 4.9.4 et Qt 5.2.0 avec mingw 4.8 sur un autre PC et j'ai le même problème.

j'utilise la version CEF 3.2272.32 alors que dans ton wiki il est indiqué CEF 3.2272.2077

cela peu avoir un impact ?

**Comment by GreatTux** [comment]
Oui c'est fort possible que la version de CEF induise cela. Surtout que le dossier patché que j'ai poussé sur le dépôt n'a normalement pas été modifié de ton côté. Ce qui voudrait dire que dans ton cas, le projet mélange de la 3.2272.32 et de la 3.2272.2077. Et ça déjà c'est pas bon signe.

**Comment by bellicheone** [comment]
Avez vous encore les sources de CEF 3.2272.2077?

sinon si je path une version différente avec votre fichier DIFF cela pourra fonctionner ?

**Comment by bellicheone** [comment]
c'est bon j'ai trouvé les sources de CEF 3.2272.2077 je test cela demain.

**Comment by bellicheone** [comment]
Je viens donc de tester avec  CEF 3.2272.2077 et cela fonctionne maintenant.

Parcontre, j'ai besion d'utiliser de l'authentification! d'après mes recherches, je dois utiliser la function 
GetAuthCredentials de la class CefRequestHandler. j'ai donc implementé cela dans la clasee clienthandler mais je ne rentre jamais dans la function  !

Avez vous déjà utiliser cela?

**Comment by GreatTux** [comment]
Bonjour,

Il faut implémenter la méthode suivante de CefClient dans ClientHandler, si cela n'a pas été fait :

```
virtual CefRefPtr<CefRequestHandler> GetRequestHandler()
```

**Comment by bellicheone** [comment]
J'ai bien ajouté la ligne ci dessous dans le fichier clienthandler.h
virtual CefRefPtr<CefRequestHandler> GetRequestHandler () override { return this; }

puis j'ai reimplémenté cette function 
bool ClientHandler::GetAuthCredentials(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, bool isProxy, const CefString &host, int port, const CefString &realm, const CefString &scheme, CefRefPtr<CefAuthCallback> callback)
{
    CEF_REQUIRE_UI_THREAD();
    QMessageBox::information(0x0,"","GetAuthCredentials");
    if(isProxy)
    {
        QMessageBox::information(0x0,"","GetAuthCredentials isProxy");
        callback->Continue("e2", "e2");
        return true;
    }
    else
        QMessageBox::information(0x0,"","GetAuthCredentials NO Proxy");
    return false;
}

J'ai constasté que si j'ai pas de proxy dans les paramètres d'internet explorer je n'ai pas de crash de l'app par contre si j'ai un proxy l'app crash

Voici le debug avec l'utilisation d'un proxy dans internet explorer

J'ai l'impression qu'il m'aime pas le thread et l'utilisation d'un proxy!!

Trace debug
//*********************************************************************************************************************
[0701/170222:FATAL:clienthandler.cpp(157)] Check failed: CefCurrentlyOn(TID_UI). 

Backtrace:
    cef_trace_event_instant [0x126246F1+1451297]
    cef_trace_event_instant [0x125539FF+596015]
    cef_log [0x124BF592+82](No symbol) [0x00408EC8](No symbol) [0x00402845](No symbol) [0x00424C83]
    cef_request_context_get_global_context [0x122AA9AB+4315]
    cef_trace_event_instant [0x124FFC45+252533]
    SetCrashKeyValueImpl [0x14B7A77F+3840591]
    SetCrashKeyValueImpl [0x14A6A7FE+2726606]
    SetCrashKeyValueImpl [0x14A877F5+2845381]
    SetCrashKeyValueImpl [0x149F8B92+2260578]
    SetCrashKeyValueImpl [0x149FC783+2275923]
    SetCrashKeyValueImpl [0x149FC4BD+2275213]
    SetCrashKeyValueImpl [0x149F948E+2262878]
    SetCrashKeyValueImpl [0x149FC120+2274288]
    SetCrashKeyValueImpl [0x149F81B7+2258055]
    SetCrashKeyValueImpl [0x149FBB2B+2272763]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CAC3EE+5093054]
    SetCrashKeyValueImpl [0x14CBBCA1+5156721]
    SetCrashKeyValueImpl [0x14CB72A2+5137778]
    SetCrashKeyValueImpl [0x14CBB848+5155608]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CB1F1F+5116399]
    SetCrashKeyValueImpl [0x14CB6D94+5136484]
    SetCrashKeyValueImpl [0x14CB3982+5123154]
    SetCrashKeyValueImpl [0x14CB80ED+5141437]
    SetCrashKeyValueImpl [0x14CBBE8A+5157210]
    SetCrashKeyValueImpl [0x14CB719F+5137519]
    SetCrashKeyValueImpl [0x14CBB722+5155314]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14E687A3+6912627]
    SetCrashKeyValueImpl [0x14E6C408+6928088]
    SetCrashKeyValueImpl [0x14E6E5E0+6936752]
    SetCrashKeyValueImpl [0x14E6BE17+6926567]
    SetCrashKeyValueImpl [0x14E6E36B+6936123]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x1504F7DD+8907437]
    SetCrashKeyValueImpl [0x1505030A+8910298]
    SetCrashKeyValueImpl [0x1504F59F+8906863]
    SetCrashKeyValueImpl [0x150500D2+8909730]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CE9DCE+5345438]
    SetCrashKeyValueImpl [0x14CEADB7+5349511]
    SetCrashKeyValueImpl [0x14CEA8C4+5348244]
    SetCrashKeyValueImpl [0x14CEAD39+5349385]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CE54E9+5326777]
    SetCrashKeyValueImpl [0x14CE6F6C+5333564]
    cef_trace_event_instant [0x12686DAC+1854428]
    cef_trace_event_instant [0x12686D4A+1854330]
    cef_trace_event_instant [0x12686C7F+1854127]
    cef_trace_event_instant [0x12686D0B+1854267]
    cef_string_list_value [0x1230AE3F+219695]
    cef_trace_event_instant [0x1265EA4B+1689723]
    cef_trace_event_instant [0x1258051D+779085]
    cef_trace_event_instant [0x1257E3C4+770548]
    cef_trace_event_instant [0x1257E9AD+772061]
    cef_trace_event_instant [0x126626D2+1705218]
    cef_trace_event_instant [0x12664142+1711986]
    cef_trace_event_instant [0x126640AC+1711836]

[0701/170222:FATAL:clienthandler.cpp(157)] Check failed: CefCurrentlyOn(TID_UI). 

Backtrace:
    cef_trace_event_instant [0x126246F1+1451297]
    cef_trace_event_instant [0x125539FF+596015]
    cef_log [0x124BF592+82](No symbol) [0x00408EC8](No symbol) [0x00402845](No symbol) [0x00424C83]
    cef_request_context_get_global_context [0x122AA9AB+4315]
    cef_trace_event_instant [0x124FFC45+252533]
    SetCrashKeyValueImpl [0x14B7A77F+3840591]
    SetCrashKeyValueImpl [0x14A6A7FE+2726606]
    SetCrashKeyValueImpl [0x14A877F5+2845381]
    SetCrashKeyValueImpl [0x149F8B92+2260578]
    SetCrashKeyValueImpl [0x149FC783+2275923]
    SetCrashKeyValueImpl [0x149FC4BD+2275213]
    SetCrashKeyValueImpl [0x149F948E+2262878]
    SetCrashKeyValueImpl [0x149FC120+2274288]
    SetCrashKeyValueImpl [0x149F81B7+2258055]
    SetCrashKeyValueImpl [0x149FBB2B+2272763]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CAC3EE+5093054]
    SetCrashKeyValueImpl [0x14CBBCA1+5156721]
    SetCrashKeyValueImpl [0x14CB72A2+5137778]
    SetCrashKeyValueImpl [0x14CBB848+5155608]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CB1F1F+5116399]
    SetCrashKeyValueImpl [0x14CB6D94+5136484]
    SetCrashKeyValueImpl [0x14CB3982+5123154]
    SetCrashKeyValueImpl [0x14CB80ED+5141437]
    SetCrashKeyValueImpl [0x14CBBE8A+5157210]
    SetCrashKeyValueImpl [0x14CB719F+5137519]
    SetCrashKeyValueImpl [0x14CBB722+5155314]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14E687A3+6912627]
    SetCrashKeyValueImpl [0x14E6C408+6928088]
    SetCrashKeyValueImpl [0x14E6E5E0+6936752]
    SetCrashKeyValueImpl [0x14E6BE17+6926567]
    SetCrashKeyValueImpl [0x14E6E36B+6936123]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x1504F7DD+8907437]
    SetCrashKeyValueImpl [0x1505030A+8910298]
    SetCrashKeyValueImpl [0x1504F59F+8906863]
    SetCrashKeyValueImpl [0x150500D2+8909730]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CE9DCE+5345438]
    SetCrashKeyValueImpl [0x14CEADB7+5349511]
    SetCrashKeyValueImpl [0x14CEA8C4+5348244]
    SetCrashKeyValueImpl [0x14CEAD39+5349385]
    cef_time_to_timet [0x1245EB2C+859468]
    SetCrashKeyValueImpl [0x14CE54E9+5326777]
    SetCrashKeyValueImpl [0x14CE6F6C+5333564]
    cef_trace_event_instant [0x12686DAC+1854428]
    cef_trace_event_instant [0x12686D4A+1854330]
    cef_trace_event_instant [0x12686C7F+1854127]
    cef_trace_event_instant [0x12686D0B+1854267]
    cef_string_list_value [0x1230AE3F+219695]
    cef_trace_event_instant [0x1265EA4B+1689723]
    cef_trace_event_instant [0x1258051D+779085]
    cef_trace_event_instant [0x1257E3C4+770548]
    cef_trace_event_instant [0x1257E9AD+772061]
    cef_trace_event_instant [0x126626D2+1705218]
    cef_trace_event_instant [0x12664142+1711986]
    cef_trace_event_instant [0x126640AC+1711836]

**Comment by bellicheone** [comment]
C'est j'ai réussi a faire ce que je voulais.

Maintenant, je voulais savoir comment mettre le projet CMake en Projet Qt avec un fichier pro ?

**Comment by GreatTux** [comment]
Bonjour,
Votre problématique actuelle dépasse le cadre de ce projet. J'espère que vous avez pu avancer sur cette tâche, dans le cas contraire vous pouvez prendre contact avec la communauté Qt/CMake.
