### ISSUE TITLE
can't build by qt's qmake

### ISSUE THREAD

**Issue by zileyuan** [GreatTux/CefMinGWQt#3]
I build out libcef_dll_wrapper.a by your cmake, then i change the cefqtclient to qt's project, and add LIBS += -lcef_dll_wrapper -lcef, but error when build, do you know why? only can build by cmake? thanks!

**Comment by zileyuan** [comment]
error:
cef_logging.cc: -1: error: undefined reference to `__stack_chk_guard'

: -1: error: C:/qtcef/cef/libcef_dll_wrapper.a(cef_logging.cc.obj): bad reloc address 0x50f in section `.text$_ZN3cef7logging23SystemErrorCodeToStringEm'

**Comment by GreatTux** [comment]
Hello,

No, it's not mandatory to stick to CMake. I used it because I know it and because the Cef client example is using it aswell.
Regarding your problem, I don't know why at the moment, but if you share your .pro I can have look.

**Comment by zileyuan** [comment]
thanks, i have find problem and clear up！

**Comment by toby20130333** [comment]
@zileyuan how to solve this error? thank you
